server:
 port: 8081
spring:
 application:
  name: user-body-parameters
 datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your_health_tracker_db
    username: root
    password: root
 jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
 config:
    import: "optional:configserver:http://localhost:8082/"
    
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

