server:
  port: 9010

spring:
  application:
    name: "email-message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
      kafka:
       binder:
        broker:
         -localhost:9092